export const USALI_STRUCTURE = [
    { code: '', name: 'Receita de Apartamentos', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Café da Manhã - Incluso na diária', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Alimentos - Incluso na diária', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Bebidas - Incluso na diária', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Servicos Termas - Incluso na diária', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Servico de Transporte - Incluso na diária', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Hospedagem DPA', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de ISS', package: 'HOSPEDAGEM', master: 'RECEITAS' },
    { code: '', name: 'Receita de Alimentos', package: 'ALIMENTOS E BEBIDAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Bebidas', package: 'ALIMENTOS E BEBIDAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Bebidas Monofásicas', package: 'ALIMENTOS E BEBIDAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Coffee Break', package: 'ALIMENTOS E BEBIDAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Aluguel de Salas', package: 'EVENTOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Aluguel de Equipamentos', package: 'EVENTOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Internet', package: 'EVENTOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Telefonia', package: 'EVENTOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de ISS', package: 'EVENTOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Mercadorias Diversas', package: 'VENDAS DIVERSAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Produtos Diversos - Lojas', package: 'VENDAS DIVERSAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Produtos ST', package: 'VENDAS DIVERSAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Vestuarios', package: 'VENDAS DIVERSAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Produtos Diversos - A&B', package: 'VENDAS DIVERSAS', master: 'RECEITAS' },
    { code: '', name: 'Vendas de reciclaveis', package: 'VENDAS DIVERSAS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Lavanderia', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Servicos Diversos', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Serviço Spa/ Termas', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita Taxa Serviço (Sobre Serviços)', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita Day Use', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Estacionamento', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de Boliche', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Cancelamento de Time Share', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Receita de ISS', package: 'OUTROS SERVICOS', master: 'RECEITAS' },
    { code: '', name: 'Carnes / Aves / Peixes', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Condimentos / Conservas', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Embutidos / Massas', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Frios', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Guloseimas', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Hortifrutigranjeiros', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Laticinios', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Outros custos', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Paes / Biscoitos', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Secos', package: 'CUSTO DE ALIMENTOS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Bebidas alcoolicas', package: 'CUSTO DE BEBIDAS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Bebidas nao alcoolicas', package: 'CUSTO DE BEBIDAS', master: 'CUSTOS DE ALIMENTOS E BEBIDAS' },
    { code: '', name: 'Cigarros', package: 'CUSTO DE PRODUTOS DIVERSOS', master: 'CUSTO DE PRODUTOS DIVERSOS' },
    { code: '', name: 'Custos Descartaveis', package: 'CUSTO DE PRODUTOS DIVERSOS', master: 'CUSTO DE PRODUTOS DIVERSOS' },
    { code: '', name: 'Custos Diversos', package: 'CUSTO DE PRODUTOS DIVERSOS', master: 'CUSTO DE PRODUTOS DIVERSOS' },
    { code: '', name: 'Diversos A&B', package: 'CUSTO DE PRODUTOS DIVERSOS', master: 'CUSTO DE PRODUTOS DIVERSOS' },
    { code: '', name: 'Produtos diversos lojinha', package: 'CUSTO DE PRODUTOS DIVERSOS', master: 'CUSTO DE PRODUTOS DIVERSOS' },
    { code: '', name: 'Vestuario', package: 'CUSTO DE PRODUTOS DIVERSOS', master: 'CUSTO DE PRODUTOS DIVERSOS' },
    { code: '', name: 'Custo com entretenimento', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de aluguel de equipamentos', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de estacionamento', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de internet', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de lavanderia hospedes', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de servico de fotografia', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de servico de massagens', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de telefonia', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Custo de transporte de clientes', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Outros custos de servicos prestados', package: 'CUSTOS DE OUTRAS RECEITAS', master: 'CUSTOS DE OUTRAS RECEITAS' },
    { code: '', name: 'Limpeza de carpetes', package: 'DESPESAS COM CONSERVACAO E LIMPEZA', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Material de limpeza', package: 'DESPESAS COM CONSERVACAO E LIMPEZA', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Produtos de limpeza', package: 'DESPESAS COM CONSERVACAO E LIMPEZA', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Servicos de limpeza', package: 'DESPESAS COM CONSERVACAO E LIMPEZA', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Contratos de manutencao', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Ar condicionado', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Caldeira', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Elevador', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Equipamentos de TI', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Estrutura predial', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Instalacao eletrica', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Instalacao hidraulica', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Instrumentacao / automacao', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Jardins / Quadras / Animais', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Maquinas e equipamentos', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Material de consumo', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Moveis e utensilios', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Piscina', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Restauracao', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Telefonia', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reparos e materiais - Veiculo', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Servico de dedetizacao', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Servicos de remocao de lixo e entulho', package: 'DESPESAS COM MANUTENCAO', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Agua', package: 'DESPESAS COM SERVICOS PUBLICOS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Combustiveis para Geradores', package: 'DESPESAS COM SERVICOS PUBLICOS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Combustiveis para veiculos', package: 'DESPESAS COM SERVICOS PUBLICOS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Energia eletrica', package: 'DESPESAS COM SERVICOS PUBLICOS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Gas', package: 'DESPESAS COM SERVICOS PUBLICOS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Amenidades / Suprimentos pra hospedes', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Assinatura de TV a cabo', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Danos e perdas', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Decoração e ornamentos', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Despesas com descartaveis', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Despesas de Taxa de Reservas', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Falhas de Hospedagem / Overbook', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Frete', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'ICMS - Diferencial de aliquota', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Indenizacao ao hospede', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Jornais / livros / revistas', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Lavanderia enxoval', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Lavanderia uniformes', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Locacao de moveis, utensílios e equipamentos', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Material de esporte e lazer', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Material de estetica', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Musica, entretenimento e bem estar', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reposição de enxovais', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Reposição de materiais, moveis e utensílios', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Room tax (taxa de turismo)', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Seguranca / Salva vidas', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Servicos prestados por terceiros', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Suprimentos impressos e folheteria', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Telefonia fixa', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Telefonia móvel', package: 'DESPESAS OPERACIONAIS', master: 'DESPESAS GERAIS E OPERACIONAIS' },
    { code: '', name: 'Assiduidade', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Ajuda de custos', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Alojamento e casa de praia', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Assistencia medica e odontologica', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Atividades desportivas e sociais', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Brigada de incendio', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Cesta basica', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Consumo interno', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Cursos e treinamentos', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'PPRA e PCMSO', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Produtividade / Premiacao', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Refeicao (PAT)', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Seguro de vida', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Ticket alimentacao', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Vale Transporte', package: 'BENEFICIOS AOS COLABORADORES', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Acordo judicial trabalhista', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Adicional noturno', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Aviso Previo Indenizado', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Comissoes vendedoras / executivas', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Decimo terceiro salario', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Estagiarios', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Ferias', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Gratificacao', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Horas extras', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Indenizacoes trabalhistas', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Participacao nos Lucros e Resultados - PLR', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Pro labore', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Salario maternidade', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Salarios e ordenados', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Uniformes e fantasias', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'EPI e EPC', package: 'DESPESAS COM PESSOAL', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Contribuicao sindical e assistencial', package: 'ENCARGOS SOCIAIS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'FGTS', package: 'ENCARGOS SOCIAIS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'FGTS Rescisorio', package: 'ENCARGOS SOCIAIS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'INSS', package: 'ENCARGOS SOCIAIS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'PIS s/ folha de pagamento', package: 'ENCARGOS SOCIAIS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Servicos de terceiros temporarios', package: 'SERVIÇOS DE TERCEIROS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Serviço de terceiros recorrente', package: 'SERVIÇOS DE TERCEIROS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Serviços contratados de prestadores PJ - MEI', package: 'SERVIÇOS DE TERCEIROS', master: 'DESPESAS COM MAO DE OBRA' },
    { code: '', name: 'Assessoria contabil', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Assessoria e perdas com cobranca', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Assessoria jurídica e advocaticia', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Associacao de classe', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Auditoria externa', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Comissao cartao Amex', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Comissao cartao Diners', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Comissao cartao MasterCard', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Comissao cartao Visa', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Comissao Elo/ Cabal/ Hipercard/ Alelo/ Discover', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Comissoes de agencias', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Conducao, alimentacao e quilometragem', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Consultas a SERASA e SPC', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Consultoria / Assessoria', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Correio / Malote / Motoboy', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Despesas com Internet', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Despesas com veiculos', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Despesas com viagens e estadas', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Despesas de Taxa de Administracao', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Despesas Nao Dedutiveis terceiros', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Despesas Nao Dedutiveis pequenas despesas', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Direito Autoral e de Imagem', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Doacao/Donativos', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Indenizacoes e acordo judicial civil', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Licença de uso e marca', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Material de escritorio', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Multas e autuações diversas', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Processamentos de dados e TI', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Provisão Devedores Duvidosos - PDD', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Recrutamento e selecao', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Seguros', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Servicos de cartorio, autenticacoes e copias', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Suprimentos de informatica', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Taxa de condominio e aluguel de imoveis', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Taxas fiscais e legais', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Projetos Sustentáveis', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Licença de plataforma TI', package: 'DESPESAS ADMINISTRATIVAS', master: 'DESPESAS ADMINISTRATIVAS' },
    { code: '', name: 'Provisao de gastos diversos', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de servicos gerenciais', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de advogados e honorarios', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de viagens e representacoes', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de PLR', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de auditoria externa', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de roupa, cama, mesa e banho', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de material operacional', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de bonus', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de uniformes', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de fundo de reserva', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de publicidade', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de recursos humanos', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de manutencao e reparos', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de agua e esgoto', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de energia eletrica', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de combustiveis', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de telecomunicacoes', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de contingencia trabalhista', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de contingencia civel', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de servicos de terceiros temporarios', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de Taxa de Administracao', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de Taxa de Marketing', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de Taxa de Incentivo', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de PIS', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de COFINS', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de ISS', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Provisao de ICMS', package: 'PROVISOES GERAIS', master: 'PROVISOES GERAIS' },
    { code: '', name: 'Assessoria de imprensa', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Cortesias', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Despesas com fidelizacao de clientes', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Despesas de Taxa de Marketing', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Despesas de Taxa de Uso da Marca', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Divulgacao, anuncio e publicacao', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Eventos, feiras e promocoes', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Material promocional', package: 'DESPESAS COM VENDAS E MARKETING', master: 'DESPESAS COM VENDAS E MARKETING' },
    { code: '', name: 'Descontos concedidos', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Despesa Financeira / JSCP', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'IOF', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Juros e multas diversos', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Juros sobre emprestimos', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Juros sobre financiamentos', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Outras despesas financeiras', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Tarifas e despesas bancarias diversas', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Variacoes cambiais passivas', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'Variacoes monetarias passivas', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS FINANCEIRAS E BANCARIAS' },
    { code: '', name: 'CSLL', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'CSLL Diferido', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'IRPJ', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'IRPJ Diferido', package: 'IMPOSTOS SOBRE O LUCRO', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'Funrural', package: 'OUTROS IMPOSTOS', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'IPTU', package: 'OUTROS IMPOSTOS', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'IPVA', package: 'OUTROS IMPOSTOS', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'ITBI e ITR', package: 'OUTROS IMPOSTOS', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'Tributos em atraso', package: 'OUTROS IMPOSTOS', master: 'DESPESAS TRIBUTARIAS' },
    { code: '', name: 'Aluguel fixo', package: 'ARRENDAMENTO', master: 'ARRENDAMENTO' },
    { code: '', name: 'Aluguel variavel', package: 'ARRENDAMENTO', master: 'ARRENDAMENTO' },
    { code: '', name: 'Arrendamento', package: 'ARRENDAMENTO', master: 'ARRENDAMENTO' },
    { code: '', name: 'ICMS', package: 'IMPOSTOS', master: 'IMPOSTOS' },
    { code: '', name: 'COFINS', package: 'IMPOSTOS', master: 'IMPOSTOS' },
    { code: '', name: 'PIS', package: 'IMPOSTOS', master: 'IMPOSTOS' },
    { code: '', name: 'ISS', package: 'IMPOSTOS', master: 'IMPOSTOS' },
];